language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo64-8.0
- Pharo64-7.0
- Pharo32-7.0
- Pharo32-6.1
matrix:
  allow_failures:
  - smalltalk: Pharo64-8.0
  fast_finish: true
before_deploy:
  - cp "${SMALLTALK_CI_IMAGE}" "Willow-Playground.image"
  - cp "${SMALLTALK_CI_CHANGES}" "Willow-Playground.changes"
  - zip -q "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip" "Willow-Playground.image" "Willow-Playground.changes"
deploy:
  provider: releases
  api_key:
    secure: BdmboMuq9QUKirIGHKK45C6P7z4n1GEaJCcn3Z+R74bJinbfn2LKn2/1r1YyrTMglfKGV5lOryaG/jzsu3LwRd4U/MnqiSle9BQMzZL2DaEU9jt3snt5H9+PrDzHEKbLa/oSJltQOOtcBwfd0mh5N2XFAhFot1WFWBCao6U/ONCjxbTinZW0Y/JdtlBhCtQ5MU6S1xOa4TFOFYjjLCRwg6bHVqwVS8oVICdwUUD+43s8XEPLkkuS1Dch+ucjDVWN9dEnAIKBPHbmWEuir854f+LCoYfDildQwR2ofKA1s5N++Z/EZ8irbUJm7PIGiZozjWROIHmqPmTccb9kLR7GlOYCCuUsH8BB0xI3EFurgctCB0tdyFfDR8tWA1uCplAWWyp0rqIUg4PzhIeLH6Jm5BlgoXY5Ls42voh+0We+KQPJuqpHtJNXWTVclVa3sS+04EURfbxF/8KiIlFjeeYM2z3sbuVR3XjwLZ3CTd+58+o/eQxBpSxcLPG/6G6PrLR+YG7qCI/FoMXk6FoPooAoCHVZT3OC5QtYQL6nsNi5wi4PSIrEWPiZwelx1vG06vSq2G7amnXGXaXPIB+m1pjQ4EPDv7BCJVOjf8Pgrtd/im/PiENTEE6IGHNZlIw98/ZNZBx3li3Yd3E7JedLZ58Qe2T9tDDuTiTwiMLJF1P1umw=
  file: "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip"
  skip_cleanup: true
  on:
    repo: ba-st/Willow-Playground
    tags: true
