private-accessing
projectsWithLocations

	^ Array
		with: #('Willow' 'Core features, components, commands' 'https://github.com/ba-st/Willow')
		with: #('Willow-SpinKit' 'Spinner components (SpinKit)' 'https://github.com/ba-st/Willow-SpinKit')
		with: #('Willow-Bootstrap' 'Bootstrap component supplier' 'https://github.com/ba-st/Willow-Bootstrap')
		with: #('Willow-JQueryUI' 'JQueryUI component supplier' 'https://github.com/ba-st/Willow-JQueryUI')
		with: #('Willow-SemanticUI' 'SemanticUI component supplier' 'https://github.com/ba-st/Willow-SemanticUI')
		with:
			#('Willow-Playground' 'This presentation + Test Runner application' 'https://github.com/ba-st/Willow-Playground')