"
I rprovide some CSS constants
"
Class {
	#name : #Smalltalks2017CssStyles,
	#superclass : #Object,
	#category : #'Willow-Playground-Smalltalks2017-Libraries'
}

{ #category : #accessing }
Smalltalks2017CssStyles class >> browseStep [

	^ 'browseStep'
]

{ #category : #accessing }
Smalltalks2017CssStyles class >> nextStep [

	^ 'nextStep'
]

{ #category : #accessing }
Smalltalks2017CssStyles class >> presentationArea [

	^ 'presentationArea'
]

{ #category : #accessing }
Smalltalks2017CssStyles class >> previousStep [

	^ 'previousStep'
]

{ #category : #accessing }
Smalltalks2017CssStyles class >> screenshot [

	^ 'screenshot'
]

{ #category : #accessing }
Smalltalks2017CssStyles class >> stepButtonContainer [

	^ 'stepButtonContainer'
]

{ #category : #accessing }
Smalltalks2017CssStyles class >> stepContent [

	^ 'stepContent'
]
