name: Baseline Groups

on: [push,pull_request,workflow_dispatch]

jobs:
   group-loading:
    runs-on: ubuntu-latest
    name: Pharo64-13
    strategy:
      fail-fast: false
      matrix:
        load-spec: [ deployment, development ]
    steps:
      - uses: actions/checkout@v6
      - uses: ba-st-actions/pharo-ci@v10
        with:
          spec: .smalltalkci/.loading.${{ matrix.load-spec }}.ston
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10
